site_name: PathFinder
theme:
  # name: material
  # name: simple-blog
  name: terminal
  palette: dark

nav:
  - Home: index.md
  - Meet the Team: team.md
  - Project:
      - Final Overview: project/project.md
      - Mechanical Process: project/meche.md
      - Firmware & ECE Process: project/ece_firmware.md
      - Software Process: project/software.md
  - Download!: download.md

plugins:
  # - gallery:
  #     examples_dirs: docs/examples # path to your example scripts
  #     gallery_dirs: docs/generated/gallery # where to save generated gallery

  - search # make sure the search plugin is still enabled

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - toc:
      baselevel: "1"
      toc_depth: "1"

extra:
  generator: false
